/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_user (void)
{
  GtkWidget *ajouter_user;
  GtkWidget *fixed1;
  GtkWidget *nom_user;
  GtkWidget *cin_user;
  GtkWidget *tel_user;
  GtkWidget *email_user;
  GtkWidget *prenom_user;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4_hsm;
  GtkWidget *calendar1_user;
  GtkWidget *retour_ajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12_hsm;
  GtkWidget *label6_sexe;
  GtkWidget *ajouterb_user;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11_hsm;
  GtkObject *spinbutton1_user_adj;
  GtkWidget *spinbutton1_user;
  GtkWidget *label1;
  GtkWidget *radiobutton2_user;
  GSList *radiobutton2_user_group = NULL;
  GtkWidget *radiobutton1_user;
  GtkWidget *ecin_us;
  GtkWidget *etel_us;
  GtkWidget *eemail_us;
  GtkWidget *eposte_us;
  GtkWidget *eprenom_us;
  GtkWidget *label13_hsm;
  GtkWidget *enom_us;
  GtkWidget *label2_hsm;
  GtkWidget *label10_hsm;
  GtkWidget *label9_hsm;
  GtkWidget *label5_hsm;
  GtkWidget *conf_aj;
  GtkWidget *label8_hsm;
  GtkWidget *label7_hsm;
  GtkWidget *label3_hsm;
  GtkWidget *label21_hsm;
  GtkWidget *image4;
  GtkWidget *econf_us;
  GtkWidget *comboboxentry1_user;

  ajouter_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_user), _("Ajouter utilisateur"));
  gtk_window_set_position (GTK_WINDOW (ajouter_user), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_user), fixed1);
  gtk_widget_set_size_request (fixed1, 637, 800);

  nom_user = gtk_entry_new ();
  gtk_widget_show (nom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_user, 176, 144);
  gtk_widget_set_size_request (nom_user, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_user), 8226);

  cin_user = gtk_entry_new ();
  gtk_widget_show (cin_user);
  gtk_fixed_put (GTK_FIXED (fixed1), cin_user, 176, 224);
  gtk_widget_set_size_request (cin_user, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin_user), 8226);

  tel_user = gtk_entry_new ();
  gtk_widget_show (tel_user);
  gtk_fixed_put (GTK_FIXED (fixed1), tel_user, 176, 448);
  gtk_widget_set_size_request (tel_user, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel_user), 8226);

  email_user = gtk_entry_new ();
  gtk_widget_show (email_user);
  gtk_fixed_put (GTK_FIXED (fixed1), email_user, 176, 496);
  gtk_widget_set_size_request (email_user, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_user), 8226);

  prenom_user = gtk_entry_new ();
  gtk_widget_show (prenom_user);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom_user, 176, 184);
  gtk_widget_set_size_request (prenom_user, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_user), 8226);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 8, 640);
  gtk_widget_set_size_request (button1, 144, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4_hsm = gtk_label_new_with_mnemonic (_("Valider le sexe"));
  gtk_widget_show (label4_hsm);
  gtk_box_pack_start (GTK_BOX (hbox1), label4_hsm, FALSE, FALSE, 0);

  calendar1_user = gtk_calendar_new ();
  gtk_widget_show (calendar1_user);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1_user, 176, 264);
  gtk_widget_set_size_request (calendar1_user, 224, 168);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1_user),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  retour_ajouter = gtk_button_new ();
  gtk_widget_show (retour_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), retour_ajouter, 88, 744);
  gtk_widget_set_size_request (retour_ajouter, 200, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour_ajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12_hsm = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label12_hsm);
  gtk_box_pack_start (GTK_BOX (hbox3), label12_hsm, FALSE, FALSE, 0);

  label6_sexe = gtk_label_new ("");
  gtk_widget_show (label6_sexe);
  gtk_fixed_put (GTK_FIXED (fixed1), label6_sexe, 304, 640);
  gtk_widget_set_size_request (label6_sexe, 152, 32);

  ajouterb_user = gtk_button_new ();
  gtk_widget_show (ajouterb_user);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouterb_user, 360, 744);
  gtk_widget_set_size_request (ajouterb_user, 200, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajouterb_user), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11_hsm = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label11_hsm);
  gtk_box_pack_start (GTK_BOX (hbox2), label11_hsm, FALSE, FALSE, 0);

  spinbutton1_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_user_adj), 1, 0);
  gtk_widget_show (spinbutton1_user);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1_user, 176, 96);
  gtk_widget_set_size_request (spinbutton1_user, 60, 27);

  label1 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 40, 184);
  gtk_widget_set_size_request (label1, 80, 24);

  radiobutton2_user = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton2_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2_user, 288, 600);
  gtk_widget_set_size_request (radiobutton2_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_user), radiobutton2_user_group);
  radiobutton2_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_user));

  radiobutton1_user = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1_user);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_user, 176, 600);
  gtk_widget_set_size_request (radiobutton1_user, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_user), radiobutton2_user_group);
  radiobutton2_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_user));

  ecin_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le num\303\251ro du CIN</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), ecin_us, 408, 232);
  gtk_widget_set_size_request (ecin_us, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (ecin_us), TRUE);

  etel_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le num\303\251ro de t\303\251l\303\251phone</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), etel_us, 376, 456);
  gtk_widget_set_size_request (etel_us, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (etel_us), TRUE);

  eemail_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez l'email</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), eemail_us, 352, 496);
  gtk_widget_set_size_request (eemail_us, 176, 24);
  gtk_label_set_use_markup (GTK_LABEL (eemail_us), TRUE);

  eposte_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifier le poste</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), eposte_us, 376, 552);
  gtk_widget_set_size_request (eposte_us, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (eposte_us), TRUE);

  eprenom_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le pr\303\251nom</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), eprenom_us, 392, 184);
  gtk_widget_set_size_request (eprenom_us, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (eprenom_us), TRUE);

  label13_hsm = gtk_label_new (_("Nom:"));
  gtk_widget_show (label13_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label13_hsm, 48, 144);
  gtk_widget_set_size_request (label13_hsm, 48, 25);

  enom_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le nom</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), enom_us, 392, 144);
  gtk_widget_set_size_request (enom_us, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (enom_us), TRUE);

  label2_hsm = gtk_label_new (_("C.I.N:"));
  gtk_widget_show (label2_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label2_hsm, 40, 224);
  gtk_widget_set_size_request (label2_hsm, 56, 32);

  label10_hsm = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (label10_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label10_hsm, 24, 448);
  gtk_widget_set_size_request (label10_hsm, 104, 32);

  label9_hsm = gtk_label_new (_("E-mail:"));
  gtk_widget_show (label9_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label9_hsm, 40, 504);
  gtk_widget_set_size_request (label9_hsm, 48, 32);

  label5_hsm = gtk_label_new (_("L'utilisateur est:"));
  gtk_widget_show (label5_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label5_hsm, 192, 640);
  gtk_widget_set_size_request (label5_hsm, 144, 32);

  conf_aj = gtk_check_button_new_with_mnemonic (_("Confirmer l ajout"));
  gtk_widget_show (conf_aj);
  gtk_fixed_put (GTK_FIXED (fixed1), conf_aj, 64, 704);
  gtk_widget_set_size_request (conf_aj, 184, 32);

  label8_hsm = gtk_label_new (_("Poste:"));
  gtk_widget_show (label8_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label8_hsm, 32, 552);
  gtk_widget_set_size_request (label8_hsm, 72, 32);

  label7_hsm = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label7_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label7_hsm, 40, 592);
  gtk_widget_set_size_request (label7_hsm, 48, 32);

  label3_hsm = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label3_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label3_hsm, 40, 320);
  gtk_widget_set_size_request (label3_hsm, 128, 40);

  label21_hsm = gtk_label_new (_("ID"));
  gtk_widget_show (label21_hsm);
  gtk_fixed_put (GTK_FIXED (fixed1), label21_hsm, 48, 96);
  gtk_widget_set_size_request (label21_hsm, 40, 24);

  image4 = create_pixmap (ajouter_user, "16245293548418_P1C5_Implémentez-une-gestion-de-compte-pour-lutilisateur.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed1), image4, 8, 0);
  gtk_widget_set_size_request (image4, 560, 72);

  econf_us = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez la case \303\240 cocher</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), econf_us, 240, 704);
  gtk_widget_set_size_request (econf_us, 208, 24);
  gtk_label_set_use_markup (GTK_LABEL (econf_us), TRUE);

  comboboxentry1_user = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1_user);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentry1_user, 176, 552);
  gtk_widget_set_size_request (comboboxentry1_user, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Administrateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Agent-de-restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Agent-de-foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1_user), _("Etudiant"));

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button102_hsm_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_ajouter, "clicked",
                    G_CALLBACK (on_retour_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterb_user, "clicked",
                    G_CALLBACK (on_ajouter_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_user, "toggled",
                    G_CALLBACK (on_radiobutton2_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_user, "toggled",
                    G_CALLBACK (on_radiobutton1_hsm_toggled),
                    NULL);
  g_signal_connect ((gpointer) conf_aj, "toggled",
                    G_CALLBACK (on_conf_aj_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_user, ajouter_user, "ajouter_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_user, nom_user, "nom_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, cin_user, "cin_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, tel_user, "tel_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, email_user, "email_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, prenom_user, "prenom_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, button1, "button1");
  GLADE_HOOKUP_OBJECT (ajouter_user, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouter_user, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouter_user, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouter_user, label4_hsm, "label4_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, calendar1_user, "calendar1_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, retour_ajouter, "retour_ajouter");
  GLADE_HOOKUP_OBJECT (ajouter_user, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajouter_user, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajouter_user, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajouter_user, label12_hsm, "label12_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label6_sexe, "label6_sexe");
  GLADE_HOOKUP_OBJECT (ajouter_user, ajouterb_user, "ajouterb_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouter_user, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouter_user, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter_user, label11_hsm, "label11_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, spinbutton1_user, "spinbutton1_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajouter_user, radiobutton2_user, "radiobutton2_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, radiobutton1_user, "radiobutton1_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, ecin_us, "ecin_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, etel_us, "etel_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, eemail_us, "eemail_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, eposte_us, "eposte_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, eprenom_us, "eprenom_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, label13_hsm, "label13_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, enom_us, "enom_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, label2_hsm, "label2_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label10_hsm, "label10_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label9_hsm, "label9_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label5_hsm, "label5_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, conf_aj, "conf_aj");
  GLADE_HOOKUP_OBJECT (ajouter_user, label8_hsm, "label8_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label7_hsm, "label7_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label3_hsm, "label3_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, label21_hsm, "label21_hsm");
  GLADE_HOOKUP_OBJECT (ajouter_user, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajouter_user, econf_us, "econf_us");
  GLADE_HOOKUP_OBJECT (ajouter_user, comboboxentry1_user, "comboboxentry1_user");

  return ajouter_user;
}

GtkWidget*
create_afficher_user (void)
{
  GtkWidget *afficher_user;
  GtkWidget *fixed2;
  GtkWidget *image5;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entre_rechercher_user;
  GtkWidget *actualiser_user;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label14_hsm;
  GtkWidget *go_modifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label15_hsm;
  GtkWidget *rechercher_user;
  GtkWidget *image10;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1_user;
  GtkWidget *label53;
  GtkWidget *go_ajouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label17_hsm;
  GtkWidget *go_supprimer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label16_hsm;
  GtkWidget *affiche1555;
  GtkWidget *fixed6;
  GtkWidget *statique_plat;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image17;
  GtkWidget *label60_hsm;
  GtkObject *spinbutton1_semaine_adj;
  GtkWidget *spinbutton1_semaine;
  GtkWidget *num_semaine;
  GtkWidget *plat1;
  GtkWidget *plat2;
  GtkWidget *plat3;
  GtkWidget *label77_hsm;
  GtkWidget *label55_hsm;
  GtkWidget *label52_hsm;
  GtkWidget *label54_hsm;
  GtkWidget *label19;
  GtkWidget *deconn_user;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image23;
  GtkWidget *label76;

  afficher_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_user), _("Acceuil"));
  gtk_window_set_position (GTK_WINDOW (afficher_user), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (afficher_user), 600, 400);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (afficher_user), fixed2);

  image5 = create_pixmap (afficher_user, "ANGIIL-actualite-projet-AGA.jpg");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed2), image5, 0, 0);
  gtk_widget_set_size_request (image5, 1024, 176);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 144);
  gtk_widget_set_size_request (notebook1, 1024, 600);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entre_rechercher_user = gtk_entry_new ();
  gtk_widget_show (entre_rechercher_user);
  gtk_fixed_put (GTK_FIXED (fixed3), entre_rechercher_user, 752, 16);
  gtk_widget_set_size_request (entre_rechercher_user, 256, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entre_rechercher_user), 8226);

  actualiser_user = gtk_button_new ();
  gtk_widget_show (actualiser_user);
  gtk_fixed_put (GTK_FIXED (fixed3), actualiser_user, 840, 336);
  gtk_widget_set_size_request (actualiser_user, 176, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (actualiser_user), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label14_hsm = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label14_hsm);
  gtk_box_pack_start (GTK_BOX (hbox4), label14_hsm, FALSE, FALSE, 0);

  go_modifier = gtk_button_new ();
  gtk_widget_show (go_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), go_modifier, 840, 256);
  gtk_widget_set_size_request (go_modifier, 176, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (go_modifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label15_hsm = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label15_hsm);
  gtk_box_pack_start (GTK_BOX (hbox5), label15_hsm, FALSE, FALSE, 0);

  rechercher_user = gtk_button_new ();
  gtk_widget_show (rechercher_user);
  gtk_fixed_put (GTK_FIXED (fixed3), rechercher_user, 704, 16);
  gtk_widget_set_size_request (rechercher_user, 40, 32);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (rechercher_user), image10);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 0, 80);
  gtk_widget_set_size_request (scrolledwindow1, 824, 488);

  treeview1_user = gtk_tree_view_new ();
  gtk_widget_show (treeview1_user);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1_user);

  label53 = gtk_label_new (_("<span foreground=\"green\" ><b>La liste des Users dejune est :</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label53, 0, 8);
  gtk_widget_set_size_request (label53, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  go_ajouter = gtk_button_new ();
  gtk_widget_show (go_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), go_ajouter, 840, 96);
  gtk_widget_set_size_request (go_ajouter, 176, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (go_ajouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label17_hsm = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17_hsm);
  gtk_box_pack_start (GTK_BOX (hbox7), label17_hsm, FALSE, FALSE, 0);

  go_supprimer = gtk_button_new ();
  gtk_widget_show (go_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), go_supprimer, 840, 176);
  gtk_widget_set_size_request (go_supprimer, 176, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (go_supprimer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label16_hsm = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label16_hsm);
  gtk_box_pack_start (GTK_BOX (hbox6), label16_hsm, FALSE, FALSE, 0);

  affiche1555 = gtk_label_new (_("<span foreground=\"blue\" ><b>Users</b></span>"));
  gtk_widget_show (affiche1555);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), affiche1555);
  gtk_label_set_use_markup (GTK_LABEL (affiche1555), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  statique_plat = gtk_button_new ();
  gtk_widget_show (statique_plat);
  gtk_fixed_put (GTK_FIXED (fixed6), statique_plat, 272, 336);
  gtk_widget_set_size_request (statique_plat, 432, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (statique_plat), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image17 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox13), image17, FALSE, FALSE, 0);

  label60_hsm = gtk_label_new_with_mnemonic (_(" Stat\303\251stiques:"));
  gtk_widget_show (label60_hsm);
  gtk_box_pack_start (GTK_BOX (hbox13), label60_hsm, FALSE, FALSE, 0);

  spinbutton1_semaine_adj = gtk_adjustment_new (1, 1, 4, 1, 10, 10);
  spinbutton1_semaine = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_semaine_adj), 1, 0);
  gtk_widget_show (spinbutton1_semaine);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1_semaine, 824, 24);
  gtk_widget_set_size_request (spinbutton1_semaine, 136, 32);

  num_semaine = gtk_label_new (_("0"));
  gtk_widget_show (num_semaine);
  gtk_fixed_put (GTK_FIXED (fixed6), num_semaine, 528, 24);
  gtk_widget_set_size_request (num_semaine, 24, 32);

  plat1 = gtk_label_new (_("!"));
  gtk_widget_show (plat1);
  gtk_fixed_put (GTK_FIXED (fixed6), plat1, 8, 216);
  gtk_widget_set_size_request (plat1, 304, 72);

  plat2 = gtk_label_new (_("!"));
  gtk_widget_show (plat2);
  gtk_fixed_put (GTK_FIXED (fixed6), plat2, 344, 216);
  gtk_widget_set_size_request (plat2, 312, 72);

  plat3 = gtk_label_new (_("!"));
  gtk_widget_show (plat3);
  gtk_fixed_put (GTK_FIXED (fixed6), plat3, 680, 216);
  gtk_widget_set_size_request (plat3, 336, 72);

  label77_hsm = gtk_label_new (_("<span foreground=\"purple\" ><b>Semaine numero :</b></span>"));
  gtk_widget_show (label77_hsm);
  gtk_fixed_put (GTK_FIXED (fixed6), label77_hsm, 384, 8);
  gtk_widget_set_size_request (label77_hsm, 136, 64);
  gtk_label_set_use_markup (GTK_LABEL (label77_hsm), TRUE);

  label55_hsm = gtk_label_new (_("<span foreground=\"green\" ><b>Le meilleur diner est :</b></span>"));
  gtk_widget_show (label55_hsm);
  gtk_fixed_put (GTK_FIXED (fixed6), label55_hsm, 704, 128);
  gtk_widget_set_size_request (label55_hsm, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label55_hsm), TRUE);

  label52_hsm = gtk_label_new (_("<span foreground=\"green\" ><b>Le meilleur petit d\303\251juner est :</b></span>"));
  gtk_widget_show (label52_hsm);
  gtk_fixed_put (GTK_FIXED (fixed6), label52_hsm, 32, 128);
  gtk_widget_set_size_request (label52_hsm, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label52_hsm), TRUE);

  label54_hsm = gtk_label_new (_("<span foreground=\"green\" ><b>Le meilleur d\303\251juner est :</b></span>"));
  gtk_widget_show (label54_hsm);
  gtk_fixed_put (GTK_FIXED (fixed6), label54_hsm, 368, 128);
  gtk_widget_set_size_request (label54_hsm, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label54_hsm), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"blue\" ><b>Meilleur menu de la semaine</b></span>"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label19);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  deconn_user = gtk_button_new ();
  gtk_widget_show (deconn_user);
  gtk_fixed_put (GTK_FIXED (fixed2), deconn_user, 896, 8);
  gtk_widget_set_size_request (deconn_user, 120, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (deconn_user), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image23 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox19), image23, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox19), label76, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) actualiser_user, "clicked",
                    G_CALLBACK (on_actualiser_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) go_modifier, "clicked",
                    G_CALLBACK (on_go_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher_user, "clicked",
                    G_CALLBACK (on_rechercher_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1_user, "row_activated",
                    G_CALLBACK (on_treeview1_user_row_activated),
                    NULL);
  g_signal_connect ((gpointer) go_ajouter, "clicked",
                    G_CALLBACK (on_go_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) go_supprimer, "clicked",
                    G_CALLBACK (on_go_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) statique_plat, "clicked",
                    G_CALLBACK (on_statique_plat_clicked),
                    NULL);
  g_signal_connect ((gpointer) deconn_user, "clicked",
                    G_CALLBACK (on_deconn_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_user, afficher_user, "afficher_user");
  GLADE_HOOKUP_OBJECT (afficher_user, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (afficher_user, image5, "image5");
  GLADE_HOOKUP_OBJECT (afficher_user, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (afficher_user, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (afficher_user, entre_rechercher_user, "entre_rechercher_user");
  GLADE_HOOKUP_OBJECT (afficher_user, actualiser_user, "actualiser_user");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (afficher_user, image6, "image6");
  GLADE_HOOKUP_OBJECT (afficher_user, label14_hsm, "label14_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, go_modifier, "go_modifier");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (afficher_user, image7, "image7");
  GLADE_HOOKUP_OBJECT (afficher_user, label15_hsm, "label15_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, rechercher_user, "rechercher_user");
  GLADE_HOOKUP_OBJECT (afficher_user, image10, "image10");
  GLADE_HOOKUP_OBJECT (afficher_user, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (afficher_user, treeview1_user, "treeview1_user");
  GLADE_HOOKUP_OBJECT (afficher_user, label53, "label53");
  GLADE_HOOKUP_OBJECT (afficher_user, go_ajouter, "go_ajouter");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (afficher_user, image9, "image9");
  GLADE_HOOKUP_OBJECT (afficher_user, label17_hsm, "label17_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, go_supprimer, "go_supprimer");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (afficher_user, image8, "image8");
  GLADE_HOOKUP_OBJECT (afficher_user, label16_hsm, "label16_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, affiche1555, "affiche1555");
  GLADE_HOOKUP_OBJECT (afficher_user, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (afficher_user, statique_plat, "statique_plat");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (afficher_user, image17, "image17");
  GLADE_HOOKUP_OBJECT (afficher_user, label60_hsm, "label60_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, spinbutton1_semaine, "spinbutton1_semaine");
  GLADE_HOOKUP_OBJECT (afficher_user, num_semaine, "num_semaine");
  GLADE_HOOKUP_OBJECT (afficher_user, plat1, "plat1");
  GLADE_HOOKUP_OBJECT (afficher_user, plat2, "plat2");
  GLADE_HOOKUP_OBJECT (afficher_user, plat3, "plat3");
  GLADE_HOOKUP_OBJECT (afficher_user, label77_hsm, "label77_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, label55_hsm, "label55_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, label52_hsm, "label52_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, label54_hsm, "label54_hsm");
  GLADE_HOOKUP_OBJECT (afficher_user, label19, "label19");
  GLADE_HOOKUP_OBJECT (afficher_user, deconn_user, "deconn_user");
  GLADE_HOOKUP_OBJECT (afficher_user, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (afficher_user, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (afficher_user, image23, "image23");
  GLADE_HOOKUP_OBJECT (afficher_user, label76, "label76");

  return afficher_user;
}

GtkWidget*
create_supprimer1_user (void)
{
  GtkWidget *supprimer1_user;
  GtkWidget *fixed4;
  GtkWidget *conf_supp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label24_hsm;
  GtkWidget *annuler_supp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label23_hsm;
  GtkWidget *label22_hsm;

  supprimer1_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer1_user), _("supprimer"));
  gtk_window_set_position (GTK_WINDOW (supprimer1_user), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer1_user), fixed4);
  gtk_widget_set_size_request (fixed4, 368, 120);

  conf_supp = gtk_button_new ();
  gtk_widget_show (conf_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), conf_supp, 208, 80);
  gtk_widget_set_size_request (conf_supp, 160, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (conf_supp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label24_hsm = gtk_label_new_with_mnemonic (_("   Confirmer"));
  gtk_widget_show (label24_hsm);
  gtk_box_pack_start (GTK_BOX (hbox9), label24_hsm, FALSE, FALSE, 0);

  annuler_supp = gtk_button_new ();
  gtk_widget_show (annuler_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler_supp, 16, 80);
  gtk_widget_set_size_request (annuler_supp, 160, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (annuler_supp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label23_hsm = gtk_label_new_with_mnemonic (_("    Annuler"));
  gtk_widget_show (label23_hsm);
  gtk_box_pack_start (GTK_BOX (hbox8), label23_hsm, FALSE, FALSE, 0);

  label22_hsm = gtk_label_new (_("Confirmer la suppression???"));
  gtk_widget_show (label22_hsm);
  gtk_fixed_put (GTK_FIXED (fixed4), label22_hsm, 104, 0);
  gtk_widget_set_size_request (label22_hsm, 200, 48);

  g_signal_connect ((gpointer) conf_supp, "clicked",
                    G_CALLBACK (on_conf_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_supp, "clicked",
                    G_CALLBACK (on_annuler_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer1_user, supprimer1_user, "supprimer1_user");
  GLADE_HOOKUP_OBJECT (supprimer1_user, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer1_user, conf_supp, "conf_supp");
  GLADE_HOOKUP_OBJECT (supprimer1_user, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (supprimer1_user, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (supprimer1_user, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer1_user, label24_hsm, "label24_hsm");
  GLADE_HOOKUP_OBJECT (supprimer1_user, annuler_supp, "annuler_supp");
  GLADE_HOOKUP_OBJECT (supprimer1_user, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimer1_user, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer1_user, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer1_user, label23_hsm, "label23_hsm");
  GLADE_HOOKUP_OBJECT (supprimer1_user, label22_hsm, "label22_hsm");

  return supprimer1_user;
}

GtkWidget*
create_modifier1_user (void)
{
  GtkWidget *modifier1_user;
  GtkWidget *fixed5;
  GtkWidget *nom_user1;
  GtkWidget *cin_user1;
  GtkWidget *tel_user1;
  GtkWidget *email_user1;
  GtkWidget *prenom_user1;
  GtkWidget *calendar11_user;
  GtkObject *spinbutton11_user_adj;
  GtkWidget *spinbutton11_user;
  GtkWidget *label27;
  GtkWidget *anuuler_md;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image15;
  GtkWidget *label32_hsm;
  GtkWidget *button4_md;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label26;
  GtkWidget *radiobutton11_user;
  GSList *radiobutton11_user_group = NULL;
  GtkWidget *radiobutton22_user;
  GtkWidget *label33_user;
  GtkWidget *label37_hsm;
  GtkWidget *label36;
  GtkWidget *label35;
  GtkWidget *label25;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label38;
  GtkWidget *enom_us1;
  GtkWidget *eprenom_us1;
  GtkWidget *ecin_us1;
  GtkWidget *etel_us1;
  GtkWidget *eemail_us1;
  GtkWidget *eposte_us1;
  GtkWidget *checkbutton11_user;
  GtkWidget *image13;
  GtkWidget *econf_us1;
  GtkWidget *modifier_us;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image16;
  GtkWidget *label34_hsm;
  GtkWidget *comboboxentry11_user;

  modifier1_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier1_user), _("modifie utilisateur"));
  gtk_window_set_position (GTK_WINDOW (modifier1_user), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier1_user), fixed5);
  gtk_widget_set_size_request (fixed5, 637, 800);

  nom_user1 = gtk_entry_new ();
  gtk_widget_show (nom_user1);
  gtk_fixed_put (GTK_FIXED (fixed5), nom_user1, 152, 136);
  gtk_widget_set_size_request (nom_user1, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_user1), 8226);

  cin_user1 = gtk_entry_new ();
  gtk_widget_show (cin_user1);
  gtk_fixed_put (GTK_FIXED (fixed5), cin_user1, 152, 232);
  gtk_widget_set_size_request (cin_user1, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin_user1), 8226);

  tel_user1 = gtk_entry_new ();
  gtk_widget_show (tel_user1);
  gtk_fixed_put (GTK_FIXED (fixed5), tel_user1, 152, 448);
  gtk_widget_set_size_request (tel_user1, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel_user1), 8226);

  email_user1 = gtk_entry_new ();
  gtk_widget_show (email_user1);
  gtk_fixed_put (GTK_FIXED (fixed5), email_user1, 152, 496);
  gtk_widget_set_size_request (email_user1, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_user1), 8226);

  prenom_user1 = gtk_entry_new ();
  gtk_widget_show (prenom_user1);
  gtk_fixed_put (GTK_FIXED (fixed5), prenom_user1, 152, 184);
  gtk_widget_set_size_request (prenom_user1, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_user1), 8226);

  calendar11_user = gtk_calendar_new ();
  gtk_widget_show (calendar11_user);
  gtk_fixed_put (GTK_FIXED (fixed5), calendar11_user, 152, 272);
  gtk_widget_set_size_request (calendar11_user, 224, 168);
  gtk_calendar_display_options (GTK_CALENDAR (calendar11_user),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton11_user_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton11_user = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_user_adj), 1, 0);
  gtk_widget_show (spinbutton11_user);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton11_user, 160, 80);
  gtk_widget_set_size_request (spinbutton11_user, 60, 27);

  label27 = gtk_label_new (_("L'utilisateur est:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 160, 640);
  gtk_widget_set_size_request (label27, 144, 32);

  anuuler_md = gtk_button_new ();
  gtk_widget_show (anuuler_md);
  gtk_fixed_put (GTK_FIXED (fixed5), anuuler_md, 88, 744);
  gtk_widget_set_size_request (anuuler_md, 200, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (anuuler_md), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox11), image15, FALSE, FALSE, 0);

  label32_hsm = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label32_hsm);
  gtk_box_pack_start (GTK_BOX (hbox11), label32_hsm, FALSE, FALSE, 0);

  button4_md = gtk_button_new ();
  gtk_widget_show (button4_md);
  gtk_fixed_put (GTK_FIXED (fixed5), button4_md, 8, 640);
  gtk_widget_set_size_request (button4_md, 144, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button4_md), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Valider le sexe"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  radiobutton11_user = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton11_user);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton11_user, 152, 600);
  gtk_widget_set_size_request (radiobutton11_user, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11_user), radiobutton11_user_group);
  radiobutton11_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11_user));

  radiobutton22_user = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton22_user);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton22_user, 272, 600);
  gtk_widget_set_size_request (radiobutton22_user, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton22_user), radiobutton11_user_group);
  radiobutton11_user_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton22_user));

  label33_user = gtk_label_new ("");
  gtk_widget_show (label33_user);
  gtk_fixed_put (GTK_FIXED (fixed5), label33_user, 312, 640);
  gtk_widget_set_size_request (label33_user, 104, 32);

  label37_hsm = gtk_label_new (_("Modifier Nom:"));
  gtk_widget_show (label37_hsm);
  gtk_fixed_put (GTK_FIXED (fixed5), label37_hsm, 32, 128);
  gtk_widget_set_size_request (label37_hsm, 104, 40);

  label36 = gtk_label_new (_("Modifier Pr\303\251nom:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 16, 192);
  gtk_widget_set_size_request (label36, 136, 24);

  label35 = gtk_label_new (_("Modifier C.I.N:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 24, 232);
  gtk_widget_set_size_request (label35, 120, 32);

  label25 = gtk_label_new (_("Modifier\nDate de naissance:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 16, 328);
  gtk_widget_set_size_request (label25, 128, 40);

  label31 = gtk_label_new (_("Modifier Num-t\303\251l:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 8, 448);
  gtk_widget_set_size_request (label31, 144, 40);

  label30 = gtk_label_new (_("Modifier E-mail:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 16, 496);
  gtk_widget_set_size_request (label30, 112, 32);

  label29 = gtk_label_new (_("Modifier Poste:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 16, 552);
  gtk_widget_set_size_request (label29, 128, 24);

  label28 = gtk_label_new (_("Modifier Sexe:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 8, 592);
  gtk_widget_set_size_request (label28, 136, 32);

  label38 = gtk_label_new (_("Modifier ID:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 24, 80);
  gtk_widget_set_size_request (label38, 96, 24);

  enom_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le nom</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), enom_us1, 384, 136);
  gtk_widget_set_size_request (enom_us1, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (enom_us1), TRUE);

  eprenom_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le pr\303\251nom</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), eprenom_us1, 376, 184);
  gtk_widget_set_size_request (eprenom_us1, 176, 16);
  gtk_label_set_use_markup (GTK_LABEL (eprenom_us1), TRUE);

  ecin_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le num CIN</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), ecin_us1, 376, 240);
  gtk_widget_set_size_request (ecin_us1, 192, 16);
  gtk_label_set_use_markup (GTK_LABEL (ecin_us1), TRUE);

  etel_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le num\303\251ro</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), etel_us1, 416, 456);
  gtk_widget_set_size_request (etel_us1, 192, 16);
  gtk_label_set_use_markup (GTK_LABEL (etel_us1), TRUE);

  eemail_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez l'email</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), eemail_us1, 432, 504);
  gtk_widget_set_size_request (eemail_us1, 136, 16);
  gtk_label_set_use_markup (GTK_LABEL (eemail_us1), TRUE);

  eposte_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez le poste</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), eposte_us1, 432, 552);
  gtk_widget_set_size_request (eposte_us1, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (eposte_us1), TRUE);

  checkbutton11_user = gtk_check_button_new_with_mnemonic (_("Confirmer la modification"));
  gtk_widget_show (checkbutton11_user);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton11_user, 32, 696);
  gtk_widget_set_size_request (checkbutton11_user, 224, 32);

  image13 = create_pixmap (modifier1_user, "16245293548418_P1C5_Implémentez-une-gestion-de-compte-pour-lutilisateur.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed5), image13, 0, 0);
  gtk_widget_set_size_request (image13, 624, 72);

  econf_us1 = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez la case \303\240 cocher</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), econf_us1, 320, 696);
  gtk_widget_set_size_request (econf_us1, 208, 24);
  gtk_label_set_use_markup (GTK_LABEL (econf_us1), TRUE);

  modifier_us = gtk_button_new ();
  gtk_widget_show (modifier_us);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_us, 360, 744);
  gtk_widget_set_size_request (modifier_us, 200, 56);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (modifier_us), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image16 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox12), image16, FALSE, FALSE, 0);

  label34_hsm = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label34_hsm);
  gtk_box_pack_start (GTK_BOX (hbox12), label34_hsm, FALSE, FALSE, 0);

  comboboxentry11_user = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry11_user);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry11_user, 152, 544);
  gtk_widget_set_size_request (comboboxentry11_user, 216, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Administrateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Agent-de-restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Agent-de-foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry11_user), _("Etudiant"));

  g_signal_connect ((gpointer) anuuler_md, "clicked",
                    G_CALLBACK (on_anuuler_md_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_md, "clicked",
                    G_CALLBACK (on_button4_md_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11_user, "toggled",
                    G_CALLBACK (on_radiobutton11_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton22_user, "toggled",
                    G_CALLBACK (on_radiobutton22_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton11_user, "toggled",
                    G_CALLBACK (on_checkbutton11_user_toggled),
                    NULL);
  g_signal_connect ((gpointer) modifier_us, "clicked",
                    G_CALLBACK (on_modifier_us_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier1_user, modifier1_user, "modifier1_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier1_user, nom_user1, "nom_user1");
  GLADE_HOOKUP_OBJECT (modifier1_user, cin_user1, "cin_user1");
  GLADE_HOOKUP_OBJECT (modifier1_user, tel_user1, "tel_user1");
  GLADE_HOOKUP_OBJECT (modifier1_user, email_user1, "email_user1");
  GLADE_HOOKUP_OBJECT (modifier1_user, prenom_user1, "prenom_user1");
  GLADE_HOOKUP_OBJECT (modifier1_user, calendar11_user, "calendar11_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, spinbutton11_user, "spinbutton11_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier1_user, anuuler_md, "anuuler_md");
  GLADE_HOOKUP_OBJECT (modifier1_user, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modifier1_user, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier1_user, image15, "image15");
  GLADE_HOOKUP_OBJECT (modifier1_user, label32_hsm, "label32_hsm");
  GLADE_HOOKUP_OBJECT (modifier1_user, button4_md, "button4_md");
  GLADE_HOOKUP_OBJECT (modifier1_user, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier1_user, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier1_user, image14, "image14");
  GLADE_HOOKUP_OBJECT (modifier1_user, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier1_user, radiobutton11_user, "radiobutton11_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, radiobutton22_user, "radiobutton22_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, label33_user, "label33_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, label37_hsm, "label37_hsm");
  GLADE_HOOKUP_OBJECT (modifier1_user, label36, "label36");
  GLADE_HOOKUP_OBJECT (modifier1_user, label35, "label35");
  GLADE_HOOKUP_OBJECT (modifier1_user, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifier1_user, label31, "label31");
  GLADE_HOOKUP_OBJECT (modifier1_user, label30, "label30");
  GLADE_HOOKUP_OBJECT (modifier1_user, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier1_user, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifier1_user, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifier1_user, enom_us1, "enom_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, eprenom_us1, "eprenom_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, ecin_us1, "ecin_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, etel_us1, "etel_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, eemail_us1, "eemail_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, eposte_us1, "eposte_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, checkbutton11_user, "checkbutton11_user");
  GLADE_HOOKUP_OBJECT (modifier1_user, image13, "image13");
  GLADE_HOOKUP_OBJECT (modifier1_user, econf_us1, "econf_us1");
  GLADE_HOOKUP_OBJECT (modifier1_user, modifier_us, "modifier_us");
  GLADE_HOOKUP_OBJECT (modifier1_user, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier1_user, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier1_user, image16, "image16");
  GLADE_HOOKUP_OBJECT (modifier1_user, label34_hsm, "label34_hsm");
  GLADE_HOOKUP_OBJECT (modifier1_user, comboboxentry11_user, "comboboxentry11_user");

  return modifier1_user;
}

GtkWidget*
create_auth_user (void)
{
  GtkWidget *auth_user;
  GtkWidget *fixed7;
  GtkWidget *entry1_user;
  GtkWidget *entry2_pass;
  GtkWidget *hseparator1;
  GtkWidget *login_user;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label63_hsm;
  GtkWidget *inscri_user;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image21;
  GtkWidget *label71_hsm;
  GtkWidget *label69_hsm;
  GtkWidget *erreur_pass;
  GtkWidget *label61_hsm;
  GtkWidget *label62_hsm;

  auth_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (auth_user), _("Authentification"));
  gtk_window_set_position (GTK_WINDOW (auth_user), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (auth_user), fixed7);
  gtk_widget_set_size_request (fixed7, 472, 472);

  entry1_user = gtk_entry_new ();
  gtk_widget_show (entry1_user);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1_user, 80, 176);
  gtk_widget_set_size_request (entry1_user, 344, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_user), 8226);

  entry2_pass = gtk_entry_new ();
  gtk_widget_show (entry2_pass);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2_pass, 80, 272);
  gtk_widget_set_size_request (entry2_pass, 344, 48);
  gtk_entry_set_visibility (GTK_ENTRY (entry2_pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_pass), 8226);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed7), hseparator1, 40, 400);
  gtk_widget_set_size_request (hseparator1, 432, 16);

  login_user = gtk_button_new ();
  gtk_widget_show (login_user);
  gtk_fixed_put (GTK_FIXED (fixed7), login_user, 144, 344);
  gtk_widget_set_size_request (login_user, 216, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (login_user), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label63_hsm = gtk_label_new_with_mnemonic (_("S'authentifier"));
  gtk_widget_show (label63_hsm);
  gtk_box_pack_start (GTK_BOX (hbox14), label63_hsm, FALSE, FALSE, 0);

  inscri_user = gtk_button_new ();
  gtk_widget_show (inscri_user);
  gtk_fixed_put (GTK_FIXED (fixed7), inscri_user, 96, 424);
  gtk_widget_set_size_request (inscri_user, 320, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (inscri_user), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image21 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox17), image21, FALSE, FALSE, 0);

  label71_hsm = gtk_label_new_with_mnemonic (_("Aller \303\240 l'inscription"));
  gtk_widget_show (label71_hsm);
  gtk_box_pack_start (GTK_BOX (hbox17), label71_hsm, FALSE, FALSE, 0);

  label69_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>Authentification</b></span>"));
  gtk_widget_show (label69_hsm);
  gtk_fixed_put (GTK_FIXED (fixed7), label69_hsm, 160, 16);
  gtk_widget_set_size_request (label69_hsm, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label69_hsm), TRUE);

  erreur_pass = gtk_label_new (_("<span foreground=\"red\" ><b>V\303\251rifiez vos informations</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), erreur_pass, 136, 96);
  gtk_widget_set_size_request (erreur_pass, 216, 32);
  gtk_label_set_use_markup (GTK_LABEL (erreur_pass), TRUE);

  label61_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>Username</b></span>"));
  gtk_widget_show (label61_hsm);
  gtk_fixed_put (GTK_FIXED (fixed7), label61_hsm, 0, 136);
  gtk_widget_set_size_request (label61_hsm, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label61_hsm), TRUE);

  label62_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>Password</b></span>"));
  gtk_widget_show (label62_hsm);
  gtk_fixed_put (GTK_FIXED (fixed7), label62_hsm, 8, 232);
  gtk_widget_set_size_request (label62_hsm, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label62_hsm), TRUE);

  g_signal_connect ((gpointer) login_user, "clicked",
                    G_CALLBACK (on_login_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) inscri_user, "clicked",
                    G_CALLBACK (on_inscri_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (auth_user, auth_user, "auth_user");
  GLADE_HOOKUP_OBJECT (auth_user, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (auth_user, entry1_user, "entry1_user");
  GLADE_HOOKUP_OBJECT (auth_user, entry2_pass, "entry2_pass");
  GLADE_HOOKUP_OBJECT (auth_user, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (auth_user, login_user, "login_user");
  GLADE_HOOKUP_OBJECT (auth_user, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (auth_user, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (auth_user, image18, "image18");
  GLADE_HOOKUP_OBJECT (auth_user, label63_hsm, "label63_hsm");
  GLADE_HOOKUP_OBJECT (auth_user, inscri_user, "inscri_user");
  GLADE_HOOKUP_OBJECT (auth_user, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (auth_user, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (auth_user, image21, "image21");
  GLADE_HOOKUP_OBJECT (auth_user, label71_hsm, "label71_hsm");
  GLADE_HOOKUP_OBJECT (auth_user, label69_hsm, "label69_hsm");
  GLADE_HOOKUP_OBJECT (auth_user, erreur_pass, "erreur_pass");
  GLADE_HOOKUP_OBJECT (auth_user, label61_hsm, "label61_hsm");
  GLADE_HOOKUP_OBJECT (auth_user, label62_hsm, "label62_hsm");

  return auth_user;
}

GtkWidget*
create_inscri_user (void)
{
  GtkWidget *inscri_user;
  GtkWidget *fixed8;
  GtkWidget *entre_username;
  GtkWidget *entre_password;
  GtkWidget *inscri_us;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *label68_hsm;
  GtkWidget *annuler_ins;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image22;
  GtkWidget *label72_hsm;
  GtkWidget *label100000_hsm;
  GtkWidget *label73_hsm;
  GtkWidget *label74_hsm;

  inscri_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscri_user), _("inscription"));
  gtk_window_set_position (GTK_WINDOW (inscri_user), GTK_WIN_POS_CENTER);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (inscri_user), fixed8);
  gtk_widget_set_size_request (fixed8, 472, 472);

  entre_username = gtk_entry_new ();
  gtk_widget_show (entre_username);
  gtk_fixed_put (GTK_FIXED (fixed8), entre_username, 48, 168);
  gtk_widget_set_size_request (entre_username, 376, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entre_username), 8226);

  entre_password = gtk_entry_new ();
  gtk_widget_show (entre_password);
  gtk_fixed_put (GTK_FIXED (fixed8), entre_password, 48, 256);
  gtk_widget_set_size_request (entre_password, 376, 48);
  gtk_entry_set_visibility (GTK_ENTRY (entre_password), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entre_password), 8226);

  inscri_us = gtk_button_new ();
  gtk_widget_show (inscri_us);
  gtk_fixed_put (GTK_FIXED (fixed8), inscri_us, 96, 344);
  gtk_widget_set_size_request (inscri_us, 280, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (inscri_us), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  label68_hsm = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label68_hsm);
  gtk_box_pack_start (GTK_BOX (hbox16), label68_hsm, FALSE, FALSE, 0);

  annuler_ins = gtk_button_new ();
  gtk_widget_show (annuler_ins);
  gtk_fixed_put (GTK_FIXED (fixed8), annuler_ins, 128, 408);
  gtk_widget_set_size_request (annuler_ins, 224, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_ins), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image22 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox18), image22, FALSE, FALSE, 0);

  label72_hsm = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label72_hsm);
  gtk_box_pack_start (GTK_BOX (hbox18), label72_hsm, FALSE, FALSE, 0);

  label100000_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>S'inscrire</b></span>"));
  gtk_widget_show (label100000_hsm);
  gtk_fixed_put (GTK_FIXED (fixed8), label100000_hsm, 160, 40);
  gtk_widget_set_size_request (label100000_hsm, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label100000_hsm), TRUE);

  label73_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>Username</b></span>"));
  gtk_widget_show (label73_hsm);
  gtk_fixed_put (GTK_FIXED (fixed8), label73_hsm, 0, 136);
  gtk_widget_set_size_request (label73_hsm, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label73_hsm), TRUE);

  label74_hsm = gtk_label_new (_("<span foreground=\"blue\" ><b>Password</b></span>"));
  gtk_widget_show (label74_hsm);
  gtk_fixed_put (GTK_FIXED (fixed8), label74_hsm, 8, 232);
  gtk_widget_set_size_request (label74_hsm, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label74_hsm), TRUE);

  g_signal_connect ((gpointer) inscri_us, "clicked",
                    G_CALLBACK (on_inscri_us_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_ins, "clicked",
                    G_CALLBACK (on_annuler_ins_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscri_user, inscri_user, "inscri_user");
  GLADE_HOOKUP_OBJECT (inscri_user, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (inscri_user, entre_username, "entre_username");
  GLADE_HOOKUP_OBJECT (inscri_user, entre_password, "entre_password");
  GLADE_HOOKUP_OBJECT (inscri_user, inscri_us, "inscri_us");
  GLADE_HOOKUP_OBJECT (inscri_user, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (inscri_user, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (inscri_user, image20, "image20");
  GLADE_HOOKUP_OBJECT (inscri_user, label68_hsm, "label68_hsm");
  GLADE_HOOKUP_OBJECT (inscri_user, annuler_ins, "annuler_ins");
  GLADE_HOOKUP_OBJECT (inscri_user, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (inscri_user, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (inscri_user, image22, "image22");
  GLADE_HOOKUP_OBJECT (inscri_user, label72_hsm, "label72_hsm");
  GLADE_HOOKUP_OBJECT (inscri_user, label100000_hsm, "label100000_hsm");
  GLADE_HOOKUP_OBJECT (inscri_user, label73_hsm, "label73_hsm");
  GLADE_HOOKUP_OBJECT (inscri_user, label74_hsm, "label74_hsm");

  return inscri_user;
}

