/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_user (void);
GtkWidget* create_afficher_user (void);
GtkWidget* create_supprimer1_user (void);
GtkWidget* create_modifier1_user (void);
GtkWidget* create_auth_user (void);
GtkWidget* create_inscri_user (void);
